ignored:
  - DL3013  # Pin versions in pip. (false positive)
  - DL3018  # Pin versions in apk add.
  - DL3019  # Use the `--no-cache` with apk. (unnecessary)
  - DL3042  # Avoid use of cache directory with pip. (unnecessary)
  - DL4006  # Set the SHELL option -o pipefail before RUN with a pipe in it. (false positive)
